In [31]:
import duckdb
import pandas as pd
import json
import numpy as np

# Connect to DuckDB
con = duckdb.connect(':memory:')

# First, let's see what columns we have in the parquet files
print("Schema of parquet files:")
schema = con.execute("DESCRIBE SELECT * FROM read_parquet('company_details/*.parquet', union_by_name=True)").df()
display(schema)

# Now let's examine the financials column structure
query = """
SELECT company_number, financials
FROM read_parquet('company_details/*.parquet', union_by_name=True)
WHERE financials IS NOT NULL
  AND length(financials) > 0
LIMIT 1;
"""

df = con.execute(query).df()

print("\nExamining financial data structure:")
if len(df) > 0:
    print(f"\nCompany number: {df['company_number'].iloc[0]}")
    fin_data = df['financials'].iloc[0]
    print(f"Type of financials: {type(fin_data)}")
    
    # Convert numpy types to Python native types for better display
    def convert_to_serializable(obj):
        if isinstance(obj, (np.int_, np.intc, np.intp, np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64)):
            return int(obj)
        elif isinstance(obj, (np.float_, np.float16, np.float32, np.float64)):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, pd.NA):
            return None
        elif pd.isna(obj):
            return None
        return obj
    
    # Print raw structure
    print("\nRaw structure of first financial entry:")
    if isinstance(fin_data, (list, np.ndarray)):
        if len(fin_data) > 0:
            first_entry = convert_to_serializable(fin_data[0])
            print(json.dumps(first_entry, indent=2, default=str))
            
            # If there are facts, show the structure of the first fact
            if isinstance(first_entry, dict) and 'facts' in first_entry:
                print("\nStructure of first fact:")
                if len(first_entry['facts']) > 0:
                    print(json.dumps(first_entry['facts'][0], indent=2, default=str))
    else:
        print(f"Unexpected data type: {type(fin_data)}")

Sample financial data structure:

In [4]:
# Helper functions to process JSON columns
import numpy as np

def convert_numpy_to_python(obj):
    if isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {key: convert_numpy_to_python(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_to_python(item) for item in obj]
    return obj

def process_json_column(df, column_name):
    """Process a JSON column and return it as a pandas DataFrame with normalized data"""
    if column_name not in df.columns:
        print(f"Column {column_name} not found in the dataset")
        return None
    
    # Extract and normalize the JSON data
    processed_data = []
    
    for idx, row in df.iterrows():
        data = row[column_name]
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except json.JSONDecodeError:
                continue
                
        # Convert NumPy types to Python native types
        data = convert_numpy_to_python(data)
        
        if isinstance(data, dict):
            processed_data.append(data)
        
    # Convert to DataFrame
    return pd.json_normalize(processed_data)

# Process the financials column as an example
if 'financials' in df.columns:
    financials_df = process_json_column(df, 'financials')
    if financials_df is not None:
        print("Financials Data Structure:")
        print("\nColumns in the financials data:")
        for col in financials_df.columns:
            print(f"- {col}")
        
        print("\nFinancials Data Preview:")
        display(financials_df.head())

[
  {
    "facts": [
      {
        "concept": "bus:UKCompaniesHouseRegisteredNumber",
        "context": "C",
        "period": "2023-04-01/2024-03-31",
        "unit": null,
        "value": 220603.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 2510.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 359.0
      },
      {
        "concept": "core:Debtors",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 4908.0
      },
      {
        "concept": "core:Debtors",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1409.0
      },
      {
        "concept": "core:CashBankOnHand",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 2751.0
      },
      {
        "concept": "core:CashBankOnHand",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1379.0
      },
      {
        "concept": "core:CurrentAssets",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 7659.0
      },
      {
        "concept": "core:CurrentAssets",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 2788.0
      },
      {
        "concept": "core:Creditors",
        "context": "B_GX_IG_HB_IH",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 1641.0
      },
      {
        "concept": "core:Creditors",
        "context": "E_GX_IG_HB_IH",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1790.0
      },
      {
        "concept": "core:NetCurrentAssetsLiabilities",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 6018.0
      },
      {
        "concept": "core:NetCurrentAssetsLiabilities",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 998.0
      },
      {
        "concept": "core:TotalAssetsLessCurrentLiabilities",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 8528.0
      },
      {
        "concept": "core:TotalAssetsLessCurrentLiabilities",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1357.0
      },
      {
        "concept": "core:Equity",
        "context": "B_II_IJ",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 500000.0
      },
      {
        "concept": "core:Equity",
        "context": "E_II_IJ",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 500000.0
      },
      {
        "concept": "core:Equity",
        "context": "B_II_IK",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 491472.0
      },
      {
        "concept": "core:Equity",
        "context": "E_II_IK",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 498643.0
      },
      {
        "concept": "core:Equity",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 8528.0
      },
      {
        "concept": "core:Equity",
        "context": "E",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1357.0
      },
      {
        "concept": "core:AverageNumberEmployeesDuringPeriod",
        "context": "C",
        "period": "2023-04-01/2024-03-31",
        "unit": "xbrli:pure",
        "value": 1.0
      },
      {
        "concept": "core:AverageNumberEmployeesDuringPeriod",
        "context": "F",
        "period": "2022-04-01/2023-03-31",
        "unit": "xbrli:pure",
        "value": 1.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A_GP_IO",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10029.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A_GP_IP",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 970.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10999.0
      },
      {
        "concept": "core:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment",
        "context": "C_GP_IO",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 2533.0
      },
      {
        "concept": "core:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment",
        "context": "C_GP_IP",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 0.0
      },
      {
        "concept": "core:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment",
        "context": "C",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 2533.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B_GP_IO",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 12562.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B_GP_IP",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 970.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 13532.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A_GP_IO",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 9795.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A_GP_IP",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 845.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10640.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C_GP_IO",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 357.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C_GP_IP",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 25.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C",
        "period": "2023-04-01/2024-03-31",
        "unit": "GBP",
        "value": 382.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B_GP_IO",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 10152.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B_GP_IP",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 870.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 11022.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B_GP_IO",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 2410.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B_GP_IP",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 100.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E_GP_IO",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 234.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E_GP_IP",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 125.0
      },
      {
        "concept": "core:OtherDebtors",
        "context": "B_HB_IH",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 4908.0
      },
      {
        "concept": "core:OtherDebtors",
        "context": "E_HB_IH",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1409.0
      },
      {
        "concept": "core:OtherTaxationSocialSecurityPayable",
        "context": "B_GX_IG",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 438.0
      },
      {
        "concept": "core:OtherTaxationSocialSecurityPayable",
        "context": "E_GX_IG",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 662.0
      },
      {
        "concept": "core:OtherCreditors",
        "context": "B_GX_IG",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 1203.0
      },
      {
        "concept": "core:OtherCreditors",
        "context": "E_GX_IG",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1128.0
      },
      {
        "concept": "core:Creditors",
        "context": "B_GX_IG",
        "period": "2024-03-31",
        "unit": "GBP",
        "value": 1641.0
      },
      {
        "concept": "core:Creditors",
        "context": "E_GX_IG",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1790.0
      }
    ],
    "filing_date": "2024-12-19",
    "filing_type": "AA"
  },
  {
    "facts": [
      {
        "concept": "bus:UKCompaniesHouseRegisteredNumber",
        "context": "C",
        "period": "2022-04-01/2023-03-31",
        "unit": null,
        "value": 220603.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 359.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1448.0
      },
      {
        "concept": "core:Debtors",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1409.0
      },
      {
        "concept": "core:Debtors",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 255.0
      },
      {
        "concept": "core:CashBankOnHand",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1379.0
      },
      {
        "concept": "core:CashBankOnHand",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1714.0
      },
      {
        "concept": "core:CurrentAssets",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 2788.0
      },
      {
        "concept": "core:CurrentAssets",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1969.0
      },
      {
        "concept": "core:Creditors",
        "context": "B_DN_EU_DR_EV",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1790.0
      },
      {
        "concept": "core:Creditors",
        "context": "E_DN_EU_DR_EV",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1714.0
      },
      {
        "concept": "core:NetCurrentAssetsLiabilities",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 998.0
      },
      {
        "concept": "core:NetCurrentAssetsLiabilities",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 255.0
      },
      {
        "concept": "core:TotalAssetsLessCurrentLiabilities",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1357.0
      },
      {
        "concept": "core:TotalAssetsLessCurrentLiabilities",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1703.0
      },
      {
        "concept": "core:Equity",
        "context": "B_EW_EX",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 500000.0
      },
      {
        "concept": "core:Equity",
        "context": "E_EW_EX",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 500000.0
      },
      {
        "concept": "core:Equity",
        "context": "B_EW_EY",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 498643.0
      },
      {
        "concept": "core:Equity",
        "context": "E_EW_EY",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 498297.0
      },
      {
        "concept": "core:Equity",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1357.0
      },
      {
        "concept": "core:Equity",
        "context": "E",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1703.0
      },
      {
        "concept": "core:AverageNumberEmployeesDuringPeriod",
        "context": "C",
        "period": "2022-04-01/2023-03-31",
        "unit": "xbrli:pure",
        "value": 1.0
      },
      {
        "concept": "core:AverageNumberEmployeesDuringPeriod",
        "context": "F",
        "period": "2021-04-01/2022-03-31",
        "unit": "xbrli:pure",
        "value": 1.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A_DF_FC",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 74619.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A_DF_FD",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 23388.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "A",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 98007.0
      },
      {
        "concept": "core:OtherDisposalsPropertyPlantEquipment",
        "context": "C_DF_FC",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 64590.0
      },
      {
        "concept": "core:OtherDisposalsPropertyPlantEquipment",
        "context": "C_DF_FD",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 22418.0
      },
      {
        "concept": "core:OtherDisposalsPropertyPlantEquipment",
        "context": "C",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 87008.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B_DF_FC",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10029.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B_DF_FD",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 970.0
      },
      {
        "concept": "core:PropertyPlantEquipmentGrossCost",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10999.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A_DF_FC",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 74311.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A_DF_FD",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 22248.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "A",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 96559.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C_DF_FC",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 74.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C_DF_FD",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 31.0
      },
      {
        "concept": "core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment",
        "context": "C",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 105.0
      },
      {
        "concept": "core:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment",
        "context": "C_DF_FC",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 64590.0
      },
      {
        "concept": "core:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment",
        "context": "C_DF_FD",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 21434.0
      },
      {
        "concept": "core:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment",
        "context": "C",
        "period": "2022-04-01/2023-03-31",
        "unit": "GBP",
        "value": 86024.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B_DF_FC",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 9795.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B_DF_FD",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 845.0
      },
      {
        "concept": "core:AccumulatedDepreciationImpairmentPropertyPlantEquipment",
        "context": "B",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 10640.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B_DF_FC",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 234.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "B_DF_FD",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 125.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E_DF_FC",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 308.0
      },
      {
        "concept": "core:PropertyPlantEquipment",
        "context": "E_DF_FD",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1140.0
      },
      {
        "concept": "core:OtherDebtors",
        "context": "B_DR_EV",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1409.0
      },
      {
        "concept": "core:OtherDebtors",
        "context": "E_DR_EV",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 255.0
      },
      {
        "concept": "core:OtherTaxationSocialSecurityPayable",
        "context": "B_DN_EU",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 662.0
      },
      {
        "concept": "core:OtherTaxationSocialSecurityPayable",
        "context": "E_DN_EU",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 192.0
      },
      {
        "concept": "core:OtherCreditors",
        "context": "B_DN_EU",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1128.0
      },
      {
        "concept": "core:OtherCreditors",
        "context": "E_DN_EU",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1522.0
      },
      {
        "concept": "core:Creditors",
        "context": "B_DN_EU",
        "period": "2023-03-31",
        "unit": "GBP",
        "value": 1790.0
      },
      {
        "concept": "core:Creditors",
        "context": "E_DN_EU",
        "period": "2022-03-31",
        "unit": "GBP",
        "value": 1714.0

# Financial Facts Analysis

The financial facts in the data are structured as follows:
1. Each company can have multiple filings
2. Each filing has multiple financial facts
3. Each fact has:
   - concept: The type of financial measure
   - value: The numerical value
   - unit: The currency or unit of measurement
   - period: The time period it refers to
   - context: Additional context about the measurement

In [46]:
# First, let's get the financial facts from the parquet files
import plotly.express as px
import duckdb
import pandas as pd

# Connect to DuckDB in memory
con = duckdb.connect()

# First, let's examine the structure
inspect_query = """
WITH expanded AS (
    SELECT 
        company_number,
        UNNEST(financials) as filing
    FROM read_parquet('company_details/*.parquet', union_by_name=True)
    WHERE financials IS NOT NULL
    LIMIT 1
)
SELECT 
    company_number,
    filing.*,
    unnest.* 
FROM expanded,
UNNEST(filing.facts) AS unnest
LIMIT 1;
"""

# Execute inspection query to see the structure
print("Examining facts structure:")
inspection_result = con.execute(inspect_query).df()
print("\nAvailable columns in facts:")
display(inspection_result)

# Now let's modify our main query based on the actual structure
query = """
WITH financial_facts AS (
    SELECT 
        company_number,
        filing.filing_type,
        filing.filing_date,
        unnest.period as period,
        unnest.concept as concept,
        unnest.context as context,
        TRY_CAST(unnest.value AS FLOAT) as value,
        unnest.unit
    FROM (
        SELECT 
            company_number,
            UNNEST(financials) as filing
        FROM read_parquet('company_details/*.parquet', union_by_name=True)
        WHERE financials IS NOT NULL
    ),
    UNNEST(filing.facts) AS unnest
    WHERE unnest.value IS NOT NULL
)
SELECT 
    company_number,
    filing_type,
    filing_date,
    period,
    concept,
    context,
    value,
    unit
FROM financial_facts
WHERE period IS NOT NULL
ORDER BY company_number, filing_date DESC, period DESC, concept ASC, context ASC;
"""

# Execute query and convert to DataFrame
df_financials = con.execute(query).df()

print("\nColumns in the final dataset:")
print(df_financials.columns.tolist())

if len(df_financials) > 0:
    print("\nFirst few rows of data:")
    display(df_financials.head())
    
    # Calculate summary statistics for financial amounts
    print("\nSummary by financial concept:")
    concept_summary = df_financials.groupby('concept').agg({
        'company_number': 'nunique',
        'value': ['count', 'mean', 'median', 'std', 'min', 'max']
    }).round(2)
    
    concept_summary.columns = ['num_companies', 'count', 'mean', 'median', 'std', 'min', 'max']
    display(concept_summary.sort_values('num_companies', ascending=False))
    
    # Show the distribution of units used
    print("\nUnits used for each concept:")
    unit_summary = pd.crosstab(df_financials['concept'], df_financials['unit'])
    display(unit_summary)
    
    # Create visualization for top concepts
    top_concepts = concept_summary.nlargest(10, 'count').index
    
    fig = px.box(
        df_financials[df_financials['concept'].isin(top_concepts)],
        x='concept',
        y='value',
        title='Distribution of Values for Top Financial Concepts'
    )
    fig.update_layout(
        xaxis_title="Financial Concept",
        yaxis_title="Value",
        xaxis={'tickangle': 45}
    )
    display(fig)

Examining facts structure:

Available columns in facts:

,company_number,facts,filing_date,filing_type,unnest
0,00220603,[{'concept': 'bus:UKCompaniesHouseRegisteredNu...,2024-12-19,AA,{'concept': 'bus:UKCompaniesHouseRegisteredNum...

Examining facts structure:

Available columns in facts:

,company_number,facts,filing_date,filing_type,unnest
0,00220603,[{'concept': 'bus:UKCompaniesHouseRegisteredNu...,2024-12-19,AA,{'concept': 'bus:UKCompaniesHouseRegisteredNum...

Columns in the final dataset:
['company_number', 'filing_type', 'filing_date', 'period', 'concept', 'context', 'value', 'unit']

First few rows of data:

,company_number,filing_type,filing_date,period,concept,context,value,unit
0,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B,11022.0,GBP
1,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IO,10152.0,GBP
2,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IP,870.0,GBP
3,00220603,AA,2024-12-19,2024-03-31,core:CashBankOnHand,B,2751.0,GBP
4,00220603,AA,2024-12-19,2024-03-31,core:Creditors,B_GX_IG,1641.0,GBP

Examining facts structure:

Available columns in facts:

,company_number,facts,filing_date,filing_type,unnest
0,00220603,[{'concept': 'bus:UKCompaniesHouseRegisteredNu...,2024-12-19,AA,{'concept': 'bus:UKCompaniesHouseRegisteredNum...

Columns in the final dataset:
['company_number', 'filing_type', 'filing_date', 'period', 'concept', 'context', 'value', 'unit']

First few rows of data:

,company_number,filing_type,filing_date,period,concept,context,value,unit
0,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B,11022.0,GBP
1,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IO,10152.0,GBP
2,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IP,870.0,GBP
3,00220603,AA,2024-12-19,2024-03-31,core:CashBankOnHand,B,2751.0,GBP
4,00220603,AA,2024-12-19,2024-03-31,core:Creditors,B_GX_IG,1641.0,GBP

Summary by financial concept:

,num_companies,count,mean,median,std,min,max
concept,,,,,,,
core:Equity,140,3442,241962.078125,33321.00,629635.48,0.0,8771628.0
core:Creditors,139,1985,208820.546875,26885.00,498440.05,0.0,5032391.0
core:AverageNumberEmployeesDuringPeriod,137,1012,12.530000,2.00,114.41,0.0,2687.0
core:NetCurrentAssetsLiabilities,135,1331,208274.312500,36480.00,615327.97,0.0,8670432.0
core:CurrentAssets,135,1294,378188.625000,54659.00,1016148.60,0.0,12493292.0
...,...,...,...,...,...,...,...
e:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases,1,6,248197.687500,278480.00,134811.99,74621.0,410417.0
core:WorkInProgress,1,1,5876.000000,5876.00,NaN,5876.0,5876.0
h:DirectorRemunerationBenefitsIncludingPaymentsToThirdParties,1,2,475357.000000,475357.00,1849.79,474049.0,476665.0
h:OtherNon-auditServicesEntitySubsidiariesFees,1,2,1875.000000,1875.00,176.78,1750.0,2000.0
core:DividendPerShareInterim,1,6,30.760000,26.73,21.50,0.0,55.0

Examining facts structure:

Available columns in facts:

,company_number,facts,filing_date,filing_type,unnest
0,00220603,[{'concept': 'bus:UKCompaniesHouseRegisteredNu...,2024-12-19,AA,{'concept': 'bus:UKCompaniesHouseRegisteredNum...

Columns in the final dataset:
['company_number', 'filing_type', 'filing_date', 'period', 'concept', 'context', 'value', 'unit']

First few rows of data:

,company_number,filing_type,filing_date,period,concept,context,value,unit
0,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B,11022.0,GBP
1,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IO,10152.0,GBP
2,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IP,870.0,GBP
3,00220603,AA,2024-12-19,2024-03-31,core:CashBankOnHand,B,2751.0,GBP
4,00220603,AA,2024-12-19,2024-03-31,core:Creditors,B_GX_IG,1641.0,GBP

Summary by financial concept:

,num_companies,count,mean,median,std,min,max
concept,,,,,,,
core:Equity,140,3442,241962.078125,33321.00,629635.48,0.0,8771628.0
core:Creditors,139,1985,208820.546875,26885.00,498440.05,0.0,5032391.0
core:AverageNumberEmployeesDuringPeriod,137,1012,12.530000,2.00,114.41,0.0,2687.0
core:NetCurrentAssetsLiabilities,135,1331,208274.312500,36480.00,615327.97,0.0,8670432.0
core:CurrentAssets,135,1294,378188.625000,54659.00,1016148.60,0.0,12493292.0
...,...,...,...,...,...,...,...
e:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases,1,6,248197.687500,278480.00,134811.99,74621.0,410417.0
core:WorkInProgress,1,1,5876.000000,5876.00,NaN,5876.0,5876.0
h:DirectorRemunerationBenefitsIncludingPaymentsToThirdParties,1,2,475357.000000,475357.00,1849.79,474049.0,476665.0
h:OtherNon-auditServicesEntitySubsidiariesFees,1,2,1875.000000,1875.00,176.78,1750.0,2000.0
core:DividendPerShareInterim,1,6,30.760000,26.73,21.50,0.0,55.0

Units used for each concept:

unit,GBP,pure,shares,xbrli:pure,xbrli:shares
concept,,,,,
aurep:AuditFeesExpenses,28,0,0,0,0
c:AccruedLiabilitiesDeferredIncome,4,0,0,0,0
c:AccumulatedAmortisationImpairmentIntangibleAssets,2,0,0,0,0
c:AccumulatedDepreciationImpairmentPropertyPlantEquipment,5,0,0,0,0
c:AccumulatedDepreciationNotIncludingImpairmentPropertyPlantEquipment,5,0,0,0,0
...,...,...,...,...,...
uk-gaap:TotalAssetsLessCurrentLiabilities,80,0,0,0,0
uk-gaap:TradeCreditorsWithinOneYear,12,0,0,0,0
uk-gaap:TradeDebtors,11,0,0,0,0
uk-gaap:TurnoverGrossOperatingRevenue,8,0,0,0,0
uk-gaap:ValueSharesAllotted,14,0,0,0,0

Examining facts structure:

Available columns in facts:

,company_number,facts,filing_date,filing_type,unnest
0,00220603,[{'concept': 'bus:UKCompaniesHouseRegisteredNu...,2024-12-19,AA,{'concept': 'bus:UKCompaniesHouseRegisteredNum...

Columns in the final dataset:
['company_number', 'filing_type', 'filing_date', 'period', 'concept', 'context', 'value', 'unit']

First few rows of data:

,company_number,filing_type,filing_date,period,concept,context,value,unit
0,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B,11022.0,GBP
1,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IO,10152.0,GBP
2,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IP,870.0,GBP
3,00220603,AA,2024-12-19,2024-03-31,core:CashBankOnHand,B,2751.0,GBP
4,00220603,AA,2024-12-19,2024-03-31,core:Creditors,B_GX_IG,1641.0,GBP

Summary by financial concept:

,num_companies,count,mean,median,std,min,max
concept,,,,,,,
core:Equity,140,3442,241962.078125,33321.00,629635.48,0.0,8771628.0
core:Creditors,139,1985,208820.546875,26885.00,498440.05,0.0,5032391.0
core:AverageNumberEmployeesDuringPeriod,137,1012,12.530000,2.00,114.41,0.0,2687.0
core:NetCurrentAssetsLiabilities,135,1331,208274.312500,36480.00,615327.97,0.0,8670432.0
core:CurrentAssets,135,1294,378188.625000,54659.00,1016148.60,0.0,12493292.0
...,...,...,...,...,...,...,...
e:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases,1,6,248197.687500,278480.00,134811.99,74621.0,410417.0
core:WorkInProgress,1,1,5876.000000,5876.00,NaN,5876.0,5876.0
h:DirectorRemunerationBenefitsIncludingPaymentsToThirdParties,1,2,475357.000000,475357.00,1849.79,474049.0,476665.0
h:OtherNon-auditServicesEntitySubsidiariesFees,1,2,1875.000000,1875.00,176.78,1750.0,2000.0
core:DividendPerShareInterim,1,6,30.760000,26.73,21.50,0.0,55.0

Units used for each concept:

unit,GBP,pure,shares,xbrli:pure,xbrli:shares
concept,,,,,
aurep:AuditFeesExpenses,28,0,0,0,0
c:AccruedLiabilitiesDeferredIncome,4,0,0,0,0
c:AccumulatedAmortisationImpairmentIntangibleAssets,2,0,0,0,0
c:AccumulatedDepreciationImpairmentPropertyPlantEquipment,5,0,0,0,0
c:AccumulatedDepreciationNotIncludingImpairmentPropertyPlantEquipment,5,0,0,0,0
...,...,...,...,...,...
uk-gaap:TotalAssetsLessCurrentLiabilities,80,0,0,0,0
uk-gaap:TradeCreditorsWithinOneYear,12,0,0,0,0
uk-gaap:TradeDebtors,11,0,0,0,0
uk-gaap:TurnoverGrossOperatingRevenue,8,0,0,0,0
uk-gaap:ValueSharesAllotted,14,0,0,0,0

In [47]:
df_financials

,company_number,filing_type,filing_date,period,concept,context,value,unit
0,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B,11022.0,GBP
1,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IO,10152.0,GBP
2,00220603,AA,2024-12-19,2024-03-31,core:AccumulatedDepreciationImpairmentProperty...,B_GP_IP,870.0,GBP
3,00220603,AA,2024-12-19,2024-03-31,core:CashBankOnHand,B,2751.0,GBP
4,00220603,AA,2024-12-19,2024-03-31,core:Creditors,B_GX_IG,1641.0,GBP
...,...,...,...,...,...,...,...,...
77065,01825158,AA,2015-09-28,2013-12-31,uk-gaap-pt:ProfitLossAccountReserve,previous-mud,22086.0,GBP
77066,01825158,AA,2015-09-28,2013-12-31,uk-gaap-pt:ShareCapitalAllottedCalledUpPaid,previous-mud-shareclass-ordinary-1,10400.0,GBP
77067,01825158,AA,2015-09-28,2013-12-31,uk-gaap-pt:ShareholderFunds,previous-mud,32486.0,GBP
77068,01825158,AA,2015-09-28,2013-12-31,uk-gaap-pt:StocksInventory,previous-mud,2270.0,GBP
77069,01825158,AA,2015-09-28,2013-12-31,uk-gaap-pt:TotalAssetsLessCurrentLiabilities,previous-mud,32486.0,GBP

In [48]:
str(df_financials["concept"].unique().tolist())

"['core:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'core:CashBankOnHand', 'core:Creditors', 'core:CurrentAssets', 'core:Debtors', 'core:Equity', 'core:NetCurrentAssetsLiabilities', 'core:OtherCreditors', 'core:OtherDebtors', 'core:OtherTaxationSocialSecurityPayable', 'core:PropertyPlantEquipment', 'core:PropertyPlantEquipmentGrossCost', 'core:TotalAssetsLessCurrentLiabilities', 'bus:UKCompaniesHouseRegisteredNumber', 'core:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment', 'core:AverageNumberEmployeesDuringPeriod', 'core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'core:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'core:OtherDisposalsPropertyPlantEquipment', 'frs-core:AccruedLiabilitiesDeferredIncome', 'frs-core:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'frs-core:AmountsOwedByDirectors', 'frs-core:CashBankOnHand', 'frs-core:Creditors', 'frs-core:CurrentAssets', 'frs-core:Debtors', 'frs-core:Equity', 'frs-core:FixedAssets', 'frs-core:FurtherItemCreditorsComponentTotalCreditors', 'frs-core:NetAssetsLiabilities', 'frs-core:NetCurrentAssetsLiabilities', 'frs-core:OtherTaxationSocialSecurityPayable', 'frs-core:PropertyPlantEquipment', 'frs-core:PropertyPlantEquipmentGrossCost', 'frs-core:TotalAssetsLessCurrentLiabilities', 'frs-core:Value-addedTaxPayable', 'frs-bus:UKCompaniesHouseRegisteredNumber', 'frs-core:AverageNumberEmployeesDuringPeriod', 'frs-core:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'frs-core:TotalAdditionsIncludingFromBusinessCombinationsPropertyPlantEquipment', 'frs-core:TradeCreditorsTradePayables', 'ns6:Creditors', 'ns6:CurrentAssets', 'ns6:Equity', 'ns6:FixedAssets', 'ns6:NetCurrentAssetsLiabilities', 'ns6:TotalAssetsLessCurrentLiabilities', 'ns11:UKCompaniesHouseRegisteredNumber', 'ns6:AverageNumberEmployeesDuringPeriod', 'ns5:Creditors', 'ns5:CurrentAssets', 'ns5:Equity', 'ns5:FixedAssets', 'ns5:NetCurrentAssetsLiabilities', 'ns5:TotalAssetsLessCurrentLiabilities', 'ns10:UKCompaniesHouseRegisteredNumber', 'ns5:CalledUpShareCapital', 'ns5:CashBankInHand', 'ns5:CreditorsDueWithinOneYear', 'ns5:Debtors', 'ns5:NumberSharesAllotted', 'ns5:ProfitLossAccountReserve', 'ns5:ShareCapitalAllottedCalledUpPaid', 'ns5:ShareholderFunds', 'ns5:TangibleFixedAssets', 'ns5:TangibleFixedAssetsDepreciation', 'ns5:ParValueShare', 'ns5:TangibleFixedAssetsDepreciationChargedInPeriod', 'ns7:UKCompaniesHouseRegisteredNumber', 'ns5:TangibleFixedAssetsCostOrValuation', 'ns5:TangibleFixedAssetsAdditions', 'ns5:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'ns5:BankBorrowingsOverdrafts', 'ns5:CashBankOnHand', 'ns5:InvestmentProperty', 'ns5:NetAssetsLiabilities', 'ns5:OtherCreditors', 'ns5:OtherDebtors', 'ns5:OtherTaxationSocialSecurityPayable', 'ns5:PropertyPlantEquipment', 'ns5:ProvisionsForLiabilitiesBalanceSheetSubtotal', 'ns5:AverageNumberEmployeesDuringPeriod', 'ns5:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'ns5:InvestmentPropertyFairValueModel', 'ns5:PropertyPlantEquipmentGrossCost', 'ns5:TradeDebtorsTradeReceivables', 'ns6:AccruedLiabilities', 'ns6:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'ns6:BankBorrowingsOverdrafts', 'ns6:CashBankOnHand', 'ns6:CorporationTaxPayable', 'ns6:Debtors', 'ns6:InvestmentProperty', 'ns6:InvestmentPropertyFairValueModel', 'ns6:NetAssetsLiabilities', 'ns6:OtherCreditors', 'ns6:OtherDebtors', 'ns6:PropertyPlantEquipment', 'ns6:ProvisionsForLiabilitiesBalanceSheetSubtotal', 'ns6:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'ns6:PropertyPlantEquipmentGrossCost', 'ns6:TradeCreditorsTradePayables', 'core:BankBorrowingsOverdrafts', 'core:CorporationTaxPayable', 'core:FixedAssets', 'core:Investments', 'core:InvestmentsFixedAssets', 'core:NetAssetsLiabilities', 'core:NumberSharesIssuedFullyPaid', 'core:OtherInvestmentsOtherThanLoans', 'core:TradeCreditorsTradePayables', 'direp:AdvancesCreditsDirectors', 'core:DepreciationRateUsedForPropertyPlantEquipment', 'core:ParValueShare', 'direp:AdvancesCreditsMadeInPeriodDirectors', 'direp:AdvancesCreditsRepaidInPeriodDirectors', 'core:DisposalsPropertyPlantEquipment', 'core:GainLossOnRevaluationPropertyPlantEquipmentBeforeTaxInOtherComprehensiveIncome', 'uk-bus:UKCompaniesHouseRegisteredNumber', 'core:InvestmentsInAssociatesJointVenturesParticipatingInterests', 'core:TradeDebtorsTradeReceivables', 'core:ComprehensiveIncomeExpense', 'core:ProfitLoss', 'uk-gaap-pt:CalledUpShareCapital', 'uk-gaap-pt:CreditorsDueAfterOneYear', 'uk-gaap-pt:CreditorsDueWithinOneYear', 'uk-gaap-pt:FixedAssets', 'uk-gaap-pt:IntangibleFixedAssets', 'uk-gaap-pt:IntangibleFixedAssetsAggregateAmortisationImpairment', 'uk-gaap-pt:IntangibleFixedAssetsCostOrValuation', 'uk-gaap-pt:NetAssetsLiabilitiesIncludingPensionAssetLiability', 'uk-gaap-pt:NetCurrentAssetsLiabilities', 'uk-gaap-pt:NumberSharesAllotted', 'uk-gaap-pt:ProfitLossAccountReserve', 'uk-gaap-pt:RevaluationReserve', 'uk-gaap-pt:ShareCapitalAllottedCalledUpPaid', 'uk-gaap-pt:ShareholderFunds', 'uk-gaap-pt:TotalAssetsLessCurrentLiabilities', 'uk-gaap-cd-bus:UKCompaniesHouseRegisteredNumber', 'uk-gaap-pt:IntangibleFixedAssetsAdditions', 'uk-gaap-pt:IntangibleFixedAssetsAmortisationChargedInPeriod', 'uk-gaap-pt:IntangibleFixedAssetsIncreaseDecreaseFromRevaluations', 'uk-gaap-pt:ParValueShare', 'uk-gaap-pt:OtherAggregateReserves', 'core:TotalAssets', 'core:TotalLiabilities', 'bus:DescriptionPrincipalActivities', 'core:DepreciationAmortisationImpairmentExpense', 'core:OtherOperatingExpensesFormat2', 'core:RawMaterialsConsumablesUsed', 'core:TurnoverRevenue', 'core:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal', 'core:ProvisionsForLiabilitiesBalanceSheetSubtotal', 'core:CalledUpShareCapitalNotPaidNotExpressedAsCurrentAsset', 'core:PrepaymentsAccruedIncomeNotExpressedWithinCurrentAssetSubtotal', 'uk-core:Creditors', 'uk-core:CurrentAssets', 'uk-core:Equity', 'uk-core:FixedAssets', 'uk-core:NetAssetsLiabilities', 'uk-core:NetCurrentAssetsLiabilities', 'uk-core:TotalAssetsLessCurrentLiabilities', 'core:TaxTaxCreditOnProfitOrLossOnOrdinaryActivities', 'uk-gaap:CalledUpShareCapital', 'uk-gaap:CreditorsDueWithinOneYear', 'uk-gaap:CurrentAssets', 'uk-gaap:Debtors', 'uk-gaap:FixedAssets', 'uk-gaap:NetAssetsLiabilitiesIncludingPensionAssetLiability', 'uk-gaap:NetCurrentAssetsLiabilities', 'uk-gaap:ProfitLossAccountReserve', 'uk-gaap:ShareholderFunds', 'uk-gaap:TangibleFixedAssets', 'uk-gaap:TotalAssetsLessCurrentLiabilities', 'uk-gaap:CreditorsDueAfterOneYear', 'uk-gaap:ProfitLossForPeriod', 'core:AccumulatedAmortisationImpairmentIntangibleAssets', 'core:AmountsOwedToGroupUndertakings', 'core:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases', 'core:IntangibleAssets', 'core:InvestmentsInGroupUndertakingsParticipatingInterests', 'core:TaxationIncludingDeferredTaxationBalanceSheetSubtotal', 'core:IncreaseFromAmortisationChargeForYearIntangibleAssets', 'core:IntangibleAssetsGrossCost', 'core:TotalAdditionsIncludingFromBusinessCombinationsPropertyPlantEquipment', 'core:DividendsPaid', 'core:CorporationTaxRecoverable', 'core:TotalInventories', 'aurep:NameSeniorStatutoryAuditor', 'bus:NameEntityAuditors', 'core:DividendsPaidOnShares', 'ns6:OtherTaxationSocialSecurityPayable', 'ns6:TradeDebtorsTradeReceivables', 'ns5:TradeCreditorsTradePayables', 'ns5:TotalAdditionsIncludingFromBusinessCombinationsPropertyPlantEquipment', 'ns5:DisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'ns5:DisposalsPropertyPlantEquipment', 'ns5:TotalInventories', 'ns5:AccruedLiabilities', 'ns5:Prepayments', 'ns5:StocksInventory', 'ns6:AdvancesCreditsRepaidInPeriodDirectors', 'ns6:AdvancesCreditsDirectors', 'ns6:AdvancesCreditsMadeInPeriodDirectors', 'core:DeferredTaxAssetDebtors', 'frs-core:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases', 'frs-core:IntangibleAssets', 'frs-core:IntangibleAssetsGrossCost', 'frs-core:RawMaterials', 'frs-core:TotalInventories', 'frs-core:TradeDebtorsTradeReceivables', 'frs-core:TotalAdditionsIncludingFromBusinessCombinationsIntangibleAssets', 'ns5:CorporationTaxPayable', 'ns5:BankOverdrafts', 'uk-gaap-pt:CurrentAssets', 'uk-gaap-pt:Debtors', 'uk-gaap-pt:SecuredDebts', 'uk-gaap-pt:StocksInventory', 'uk-gaap-pt:TangibleFixedAssets', 'uk-gaap-pt:TangibleFixedAssetsCostOrValuation', 'uk-gaap-pt:TangibleFixedAssetsDepreciation', 'uk-gaap-pt:TangibleFixedAssetsAdditions', 'uk-gaap-pt:TangibleFixedAssetsDepreciationChargedInPeriod', 'uk-gaap-pt:AccrualsDeferredIncome', 'uk-gaap-pt:ProvisionsForLiabilitiesCharges', 'uk-gaap-pt:SharePremiumAccount', 'uk-gaap-pt:TangibleFixedAssetsDepreciationDecreaseIncreaseOnDisposals', 'uk-gaap-pt:TangibleFixedAssetsDisposals', 'uk-gaap-pt:TangibleFixedAssetsIncreaseDecreaseFromRevaluations', 'uk-gaap-pt:TangibleFixedAssetsIncreaseDecreaseFromTransfersBetweenItems', 'ns5:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal', 'ns6:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal', 'uk-core:AverageNumberEmployeesDuringPeriod', 'uk-gaap-pt:CashBankInHand', 'uk-gaap-pt:CurrentAssetInvestments', 'ns5:AmountsOwedByGroupUndertakings', 'ns5:InvestmentsFixedAssets', 'ns5:OtherInvestmentsOtherThanLoans', 'ns5:DisposalsDecreaseInAmortisationImpairmentIntangibleAssets', 'ns5:DisposalsIntangibleAssets', 'ns5:AccumulatedAmortisationImpairmentIntangibleAssets', 'ns5:IntangibleAssetsGrossCost', 'core:AmountsOwedByRelatedParties', 'ns5:AccruedLiabilitiesDeferredIncome', 'ns5:PrepaymentsAccruedIncome', 'ns5:Provisions', 'ns5:AdditionalProvisionsIncreaseFromNewProvisionsRecognised', 'ns5:FinanceLeaseLiabilitiesPresentValueTotal', 'ns5:CorporationTaxRecoverable', 'core:AccruedLiabilities', 'core:BankBorrowings', 'core:PrepaymentsAccruedIncome', 'core:RecoverableValue-addedTax', 'core:TaxationSocialSecurityPayable', 'direp:AmountSpecificAdvanceOrCreditDirectors', 'business:UKCompaniesHouseRegisteredNumber', 'business:VersionProductionSoftware', 'direp:AmountSpecificAdvanceOrCreditMadeInPeriodDirectors', 'direp:AmountSpecificAdvanceOrCreditRepaidInPeriodDirectors', 'core:AmountsOwedByGroupUndertakingsParticipatingInterests', 'core:DeferredIncome', 'core:LoansFromDirectors', 'd:AccruedLiabilitiesDeferredIncome', 'd:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'd:BankBorrowings', 'd:BankOverdrafts', 'd:Creditors', 'd:CurrentAssets', 'd:Debtors', 'd:Equity', 'd:FixedAssets', 'd:NetAssetsLiabilities', 'd:NetCurrentAssetsLiabilities', 'd:OtherCreditors', 'd:OtherDebtors', 'd:OtherTaxationSocialSecurityPayable', 'd:PrepaymentsAccruedIncome', 'd:PropertyPlantEquipment', 'd:PropertyPlantEquipmentGrossCost', 'd:TotalAssetsLessCurrentLiabilities', 'd:TotalInventories', 'd:TradeCreditorsTradePayables', 'd:TradeDebtorsTradeReceivables', 'c:UKCompaniesHouseRegisteredNumber', 'd:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment', 'd:DepreciationRateUsedForPropertyPlantEquipment', 'd:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'd:AccumulatedDepreciationNotIncludingImpairmentPropertyPlantEquipment', 'd:CashBankOnHand', 'd:CorporationTaxPayable', 'd:ProvisionsForLiabilitiesBalanceSheetSubtotal', 'd:TaxationIncludingDeferredTaxationBalanceSheetSubtotal', 'd:DeferredTaxLiabilities', 'd:NetDeferredTaxLiabilityAsset', 'd:AverageNumberEmployeesDuringPeriod', 'd:IncreaseDecreaseInNetDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss', 'd:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'd:OtherDisposalsPropertyPlantEquipment', 'uk-core:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal', 'uk-core:PrepaymentsAccruedIncomeNotExpressedWithinCurrentAssetSubtotal', 'ns6:TotalAdditionsIncludingFromBusinessCombinationsPropertyPlantEquipment', 'uk-gaap:CashBankInHand', 'uk-gaap:NumberSharesAllotted', 'uk-gaap:ShareCapitalAllottedCalledUpPaid', 'uk-gaap:TangibleFixedAssetsCostOrValuation', 'uk-gaap:TangibleFixedAssetsDepreciation', 'uk-gaap:ParValueShare', 'uk-gaap:TangibleFixedAssetsAdditions', 'uk-gaap:TangibleFixedAssetsDepreciationChargedInPeriod', 'uk-gaap:TangibleFixedAssetsDepreciationDecreaseIncreaseOnDisposals', 'uk-gaap:TangibleFixedAssetsDepreciationOtherIncreaseDecrease', 'uk-gaap:TangibleFixedAssetsDisposals', 'uk-gaap:TangibleFixedAssetsIncreaseDecreaseFromRevaluations', 'uk-gaap:TangibleFixedAssetsIncreaseDecreaseFromTransfersBetweenItems', 'uk-gaap:OtherCreditorsAfterOneYear', 'uk-gaap:OtherCreditorsDueWithinOneYear', 'uk-gaap:OtherDebtors', 'uk-gaap:TradeCreditorsWithinOneYear', 'uk-gaap:TradeDebtors', 'frs-core:AmountsOwedToDirectors', 'frs-core:CorporationTaxPayable', 'frs-core:InvestmentsFixedAssets', 'frs-core:OtherCreditors', 'frs-core:OtherDebtors', 'frs-core:OtherInvestmentsOtherThanLoans', 'frs-core:PrepaymentsAccruedIncome', 'frs-core:TaxationIncludingDeferredTaxationBalanceSheetSubtotal', 'frs-core:DisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'frs-core:DisposalsPropertyPlantEquipment', 'frs-core:CurrentAssetInvestments', 'frs-core:InvestmentsInSubsidiaries', 'core:OtherOperatingIncomeFormat2', 'core:StaffCostsEmployeeBenefitsExpense', 'uk-bus:AddressLine1', 'core:AdministrativeExpenses', 'core:GrossProfitLoss', 'core:OperatingProfitLoss', 'core:OtherInterestReceivableSimilarIncomeFinanceIncome', 'core:ProfitLossOnOrdinaryActivitiesBeforeTax', 'core:AccruedLiabilitiesDeferredIncome', 'core:FinanceLeaseLiabilitiesPresentValueTotal', 'core:OtherInventories', 'core:CostSales', 'core:DisposalsDecreaseInAmortisationImpairmentIntangibleAssets', 'core:DisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'core:DisposalsIntangibleAssets', 'core:IncreaseDecreaseDueToTransfersBetweenClassesIntangibleAssets', 'core:IncreaseDecreaseDueToTransfersBetweenClassesPropertyPlantEquipment', 'core:InterestPayableSimilarChargesFinanceCosts', 'core:OtherIncreaseDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'core:OtherOperatingIncome', 'core:ProfitLossOnOrdinaryActivitiesAfterTax', 'core:TotalAdditionsIncludingFromBusinessCombinationsIntangibleAssets', 'core:BankOverdrafts', 'core:CalledUpShareCapitalNotPaid', 'core:CurrentAssetInvestments', 'core:TotalIncreaseDecreaseFromRevaluationsPropertyPlantEquipment', 'ns6:AmountsOwedByGroupUndertakings', 'ns6:TotalInventories', 'ns6:DisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'ns6:DisposalsPropertyPlantEquipment', 'ns6:AmountsOwedToGroupUndertakings', 'ns21:AmountSpecificAdvanceOrCreditDirectors', 'ns21:AmountSpecificAdvanceOrCreditMadeInPeriodDirectors', 'ns21:AmountSpecificAdvanceOrCreditRepaidInPeriodDirectors', 'ns6:FinanceLeaseLiabilitiesPresentValueTotal', 'ns5:InvestmentsInGroupUndertakings', 'ns5:TotalIncreaseDecreaseFromRevaluationsPropertyPlantEquipment', 'ns5:AmountsOwedToGroupUndertakings', 'core:OtherRemainingBorrowings', 'core:TotalBorrowings', 'direp:DirectorRemuneration', 'core:Prepayments', 'core:AmountsOwedToRelatedParties', 'core:GainLossOnRevaluationPropertyPlantEquipmentNetTaxInOtherComprehensiveIncome', 'core:OtherComprehensiveIncomeExpenseNetTax', 'frs-core:FurtherDepartmentItemAverageNumberEmployeesComponentAverageNumberList', 'frs-core:RecoverableValue-addedTax', 'core:AmountsOwedByGroupUndertakings', 'core:FinishedGoodsGoodsForResale', 'aurep:AuditFeesExpenses', 'core:AdditionsOtherThanThroughBusinessCombinationsIntangibleAssets', 'core:CurrentTaxForPeriod', 'core:DistributionCosts', 'core:DividendsPaidOnSharesInterim', 'core:FurtherItemInterestExpenseComponentTotalInterestExpense', 'core:GainLossDueToForeignExchangeDifferencesRecognisedInProfitOrLoss', 'core:IncreaseDecreaseInCurrentTaxFromAdjustmentForPriorPeriods', 'core:InterestIncomeOnBankDeposits', 'core:NetFinanceIncomeCosts', 'core:OtherInterestIncome', 'core:PensionOtherPost-employmentBenefitCostsOtherPensionCosts', 'core:TaxExpenseCreditApplicableTaxRate', 'core:TaxIncreaseDecreaseArisingFromGroupReliefTaxReconciliation', 'core:TaxIncreaseDecreaseFromEffectCapitalAllowancesDepreciation', 'core:TaxIncreaseDecreaseFromEffectExpensesNotDeductibleInDeterminingTaxableProfitOrLoss', 'core:TotalCurrentTaxExpenseCredit', 'core:WagesSalaries', 'direp:DirectorRemunerationBenefitsIncludingPaymentsToThirdParties', 'uk-gaap-pt:InvestmentsFixedAssets', 'uk-gaap-pt:OtherDebtorsDueAfterOneYear', 'c:AccumulatedAmortisationImpairmentIntangibleAssets', 'c:AccumulatedDepreciationImpairmentPropertyPlantEquipment', 'c:CashBankOnHand', 'c:Creditors', 'c:CurrentAssets', 'c:Debtors', 'c:Equity', 'c:FixedAssets', 'c:IntangibleAssetsGrossCost', 'c:InvestmentsFixedAssets', 'c:NetAssetsLiabilities', 'c:NetCurrentAssetsLiabilities', 'c:NumberSharesIssuedFullyPaid', 'c:PropertyPlantEquipment', 'c:PropertyPlantEquipmentGrossCost', 'c:TotalAssetsLessCurrentLiabilities', 'c:AdditionsOtherThanThroughBusinessCombinationsPropertyPlantEquipment', 'c:AverageNumberEmployeesDuringPeriod', 'c:IncreaseFromDepreciationChargeForYearPropertyPlantEquipment', 'c:OtherDisposalsDecreaseInDepreciationImpairmentPropertyPlantEquipment', 'c:OtherDisposalsPropertyPlantEquipment', 'c:ParValueShare', 'd:UKCompaniesHouseRegisteredNumber', 'c:AccumulatedDepreciationNotIncludingImpairmentPropertyPlantEquipment', 'uk-gaap:AccrualsDeferredIncome', 'uk-gaap:CalledUpShareCapitalNotPaidNotExpressedAsCurrentAsset', 'uk-gaap:PrepaymentsAccruedIncomeNotExpressedWithinCurrentAssetSubtotal', 'uk-gaap:ProvisionsForLiabilitiesCharges', 'core:DeferredTaxLiabilities', 'core:Value-addedTaxPayable', 'core:IncreaseDecreaseInDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss', 'core:NominalValueAllottedShareCapital', 'core:NumberSharesAllotted', 'frs-core:WorkInProgress', 'd:AmountsOwedByGroupUndertakings', 'd:AmountsOwedToGroupUndertakings', 'd:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases', 'd:NumberSharesIssuedFullyPaid', 'd:TaxationSocialSecurityPayable', 'd:ParValueShare', 'c:AccruedLiabilitiesDeferredIncome', 'c:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases', 'c:OtherCreditors', 'c:OtherDebtors', 'c:PrepaymentsAccruedIncome', 'c:TaxationSocialSecurityPayable', 'c:TotalInventories', 'c:TradeCreditorsTradePayables', 'c:TradeDebtorsTradeReceivables', 'ns5:NumberSharesIssuedFullyPaid', 'ns6:AccruedLiabilitiesDeferredIncome', 'ns6:NumberSharesIssuedFullyPaid', 'ns6:ParValueShare', 'uk-core:ProvisionsForLiabilitiesBalanceSheetSubtotal', 'core:AmountsOwedToGroupUndertakingsParticipatingInterests', 'core:NetDeferredTaxLiabilityAsset', 'core:DeferredTaxExpenseCreditRelatingToOriginationReversalTimingDifferences', 'uk-gaap:IntangibleFixedAssets', 'uk-gaap:IntangibleFixedAssetsCostOrValuation', 'uk-gaap:StocksInventory', 'ns5:DeferredTaxAssetDebtors', 'ns5:BankBorrowings', 'ns5:RecoverableValue-addedTax', 'uk-gaap:CapitalEmployed', 'core:BalancesWithBanks', 'core:OtherPayablesAccruedExpenses', 'core:InvestmentProperty', 'core:InvestmentPropertyFairValueModel', 'core:IncreaseDecreaseFromFairValueAdjustmentInvestmentPropertyFairValueModel', 'ns5:IntangibleAssets', 'ns6:IntangibleAssets', 'ns6:AccumulatedAmortisationImpairmentIntangibleAssets', 'ns6:IntangibleAssetsGrossCost', 'ns6:IncreaseFromAmortisationChargeForYearIntangibleAssets', 'd:IntangibleAssets', 'd:RawMaterialsConsumables', 'd:WorkInProgress', 'ns6:DividendsPaid', 'ns6:ProfitLoss', 'ns5:DividendsPaid', 'ns5:ProfitLoss', 'ns5:FutureMinimumLeasePaymentsUnderNon-cancellableOperatingLeases', 'd:AccumulatedAmortisationImpairmentIntangibleAssets', 'd:CorporationTaxRecoverable', 'd:IntangibleAssetsGrossCost', 'd:InvestmentsFixedAssets', 'd:AdditionsOtherThanThroughBusinessCombinationsIntangibleAssets', 'd:IncreaseFromAmortisationChargeForYearIntangibleAssets', 'd:TotalBorrowings', 'd:DecreaseFromReversalImpairmentLossRecognisedInProfitOrLossIntangibleAssets', 'ns20:AmountSpecificAdvanceOrCreditDirectors', 'ns20:AmountSpecificAdvanceOrCreditRepaidInPeriodDirectors', 'frs-core:AmountsOwedByGroupUndertakings', 'frs-core:AmountsOwedToGroupUndertakings', 'frs-core:FurtherItemDebtorsComponentTotalDebtors', 'ns6:InvestmentsFixedAssets', 'ns6:OtherInvestmentsOtherThanLoa

In [49]:
df_financials.to_csv("financials.csv", index=False)

In [27]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('financials.csv')

# Keywords to search for in concepts
keywords = ['cash', 'bank', 'turnover', 'revenue', 'employee', 'asset', 'liabilit', 'debt']

# Filter concepts containing these keywords
filtered_concepts = []
for concept in df['concept'].unique():
    if any(keyword.lower() in concept.lower() for keyword in keywords):
        filtered_concepts.append(concept)

print("Relevant financial concepts:")
for concept in sorted(filtered_concepts):
    if concept.startswith('core:'):
        print(concept)

Relevant financial concepts:
core:AccruedLiabilities
core:AccruedLiabilitiesDeferredIncome
core:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal
core:AccumulatedAmortisationImpairmentIntangibleAssets
core:AdditionsOtherThanThroughBusinessCombinationsIntangibleAssets
core:AmortisationExpenseIntangibleAssets
core:AmortisationImpairmentExpenseIntangibleAssets
core:AmortisationRateUsedForIntangibleAssets
core:AverageNumberEmployeesDuringPeriod
core:BalancesWithBanks
core:BankBorrowings
core:BankBorrowingsOverdrafts
core:BankOverdrafts
core:CalledUpShareCapitalNotPaidNotExpressedAsCurrentAsset
core:CashBankOnHand
core:CashCashEquivalents
core:CashCashEquivalentsCashFlowValue
core:CashOnHand
core:CurrentAssetInvestments
core:CurrentAssets
core:Debtors
core:DeferredTaxAssetDebtors
core:DeferredTaxLiabilities
core:DisposalsDecreaseInAmortisationImpairmentIntangibleAssets
core:DisposalsIntangibleAssets
core:FinanceLeaseLiabilitiesPresentValueTotal
core:FixedAssets
core:FurtherItemCashFlowFromUsedInFinancingActivitiesComponentNetCashFlowsFromUsedInFinancingActivities
core:GainLossInCashFlowsFromChangeInCreditorsTradeOtherPayables
core:GainLossInCashFlowsFromChangeInDebtorsTradeOtherReceivables
core:IncreaseDecreaseDueToTransfersBetweenClassesIntangibleAssets
core:IncreaseDecreaseInCashCashEquivalentsBeforeForeignExchangeDifferencesChangesInConsolidation
core:IncreaseDecreaseInDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss
core:IncreaseDecreaseInNetDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss
core:IncreaseFromAmortisationChargeForYearIntangibleAssets
core:IncreaseFromImpairmentLossRecognisedInOtherComprehensiveIncomeIntangibleAssets
core:IncreaseFromImpairmentLossRecognisedInProfitOrLossIntangibleAssets
core:IntangibleAssets
core:IntangibleAssetsGrossCost
core:InterestIncomeOnBankDeposits
core:InvestmentsFixedAssets
core:NetAssetsLiabilities
core:NetAssetsLiabilitiesSubsidiaries
core:NetCashGeneratedFromOperations
core:NetCurrentAssetsLiabilities
core:NetDeferredTaxLiabilityAsset
core:OtherDebtors
core:OtherDisposalsDecreaseInAmortisationImpairmentIntangibleAssets
core:OtherDisposalsIntangibleAssets
core:OtherIncreaseDecreaseInAmortisationImpairmentIntangibleAssets
core:PrepaymentsAccruedIncomeNotExpressedWithinCurrentAssetSubtotal
core:PropertyPlantEquipmentIncludingRight-of-useAssets
core:ProvisionsForLiabilitiesBalanceSheetSubtotal
core:PurchaseIntangibleAssets
core:Share-basedPaymentExpenseCashSettled
core:StaffCostsEmployeeBenefitsExpense
core:TaxDecreaseIncreaseFromEffectRevenueExemptFromTaxation
core:TotalAdditionsIncludingFromBusinessCombinationsIntangibleAssets
core:TotalAssets
core:TotalAssetsLessCurrentLiabilities
core:TotalIncreaseDecreaseFromRevaluationsIntangibleAssets
core:TotalLiabilities
core:TradeDebtorsTradeReceivables
core:TransferToNon-currentAssetsOrDisposalGroupsHeldForSaleDecreaseInAmortisationImpairmentIntangibleAssets
core:TransferToNon-currentAssetsOrDisposalGroupsHeldForSaleDecreaseInDepreciationImpairmentPropertyPlantEquipment
core:TransfersToFromNon-currentAssetsOrDisposalGroupsHeldForSaleIntangibleAssets
core:TransfersToFromNon-currentAssetsOrDisposalGroupsHeldForSalePropertyPlantEquipment
core:TurnoverRevenue
core:UsefulLifeIntangibleAssetsYears

In [ ]:
core:AccruedLiabilities
core:AccruedLiabilitiesDeferredIncome
core:AccruedLiabilitiesNotExpressedWithinCreditorsSubtotal
core:AccumulatedAmortisationImpairmentIntangibleAssets
core:AdditionsOtherThanThroughBusinessCombinationsIntangibleAssets
core:AmortisationExpenseIntangibleAssets
core:AmortisationImpairmentExpenseIntangibleAssets
core:AmortisationRateUsedForIntangibleAssets
core:AverageNumberEmployeesDuringPeriod
core:BalancesWithBanks
core:BankBorrowings
core:BankBorrowingsOverdrafts
core:BankOverdrafts
core:CalledUpShareCapitalNotPaidNotExpressedAsCurrentAsset
core:CashBankOnHand
core:CashCashEquivalents
core:CashCashEquivalentsCashFlowValue
core:CashOnHand
core:CurrentAssetInvestments
core:CurrentAssets
core:Debtors
core:DeferredTaxAssetDebtors
core:DeferredTaxLiabilities
core:DisposalsDecreaseInAmortisationImpairmentIntangibleAssets
core:DisposalsIntangibleAssets
core:FinanceLeaseLiabilitiesPresentValueTotal
core:FixedAssets
core:FurtherItemCashFlowFromUsedInFinancingActivitiesComponentNetCashFlowsFromUsedInFinancingActivities
core:GainLossInCashFlowsFromChangeInCreditorsTradeOtherPayables
core:GainLossInCashFlowsFromChangeInDebtorsTradeOtherReceivables
core:IncreaseDecreaseDueToTransfersBetweenClassesIntangibleAssets
core:IncreaseDecreaseInCashCashEquivalentsBeforeForeignExchangeDifferencesChangesInConsolidation
core:IncreaseDecreaseInDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss
core:IncreaseDecreaseInNetDeferredTaxLiabilityFromAmountRecognisedInProfitOrLoss
core:IncreaseFromAmortisationChargeForYearIntangibleAssets
core:IncreaseFromImpairmentLossRecognisedInOtherComprehensiveIncomeIntangibleAssets
core:IncreaseFromImpairmentLossRecognisedInProfitOrLossIntangibleAssets
core:IntangibleAssets
core:IntangibleAssetsGrossCost
core:InterestIncomeOnBankDeposits
core:InvestmentsFixedAssets
core:NetAssetsLiabilities
core:NetAssetsLiabilitiesSubsidiaries
core:NetCashGeneratedFromOperations
core:NetCurrentAssetsLiabilities
core:NetDeferredTaxLiabilityAsset
core:OtherDebtors
core:OtherDisposalsDecreaseInAmortisationImpairmentIntangibleAssets
core:OtherDisposalsIntangibleAssets
core:OtherIncreaseDecreaseInAmortisationImpairmentIntangibleAssets
core:PrepaymentsAccruedIncomeNotExpressedWithinCurrentAssetSubtotal
core:PropertyPlantEquipmentIncludingRight-of-useAssets
core:ProvisionsForLiabilitiesBalanceSheetSubtotal
core:PurchaseIntangibleAssets
core:Share-basedPaymentExpenseCashSettled
core:StaffCostsEmployeeBenefitsExpense
core:TaxDecreaseIncreaseFromEffectRevenueExemptFromTaxation
core:TotalAdditionsIncludingFromBusinessCombinationsIntangibleAssets
core:TotalAssets
core:TotalAssetsLessCurrentLiabilities
core:TotalIncreaseDecreaseFromRevaluationsIntangibleAssets
core:TotalLiabilities
core:TradeDebtorsTradeReceivables
core:TransferToNon-currentAssetsOrDisposalGroupsHeldForSaleDecreaseInAmortisationImpairmentIntangibleAssets
core:TransferToNon-currentAssetsOrDisposalGroupsHeldForSaleDecreaseInDepreciationImpairmentPropertyPlantEquipment
core:TransfersToFromNon-currentAssetsOrDisposalGroupsHeldForSaleIntangibleAssets
core:TransfersToFromNon-currentAssetsOrDisposalGroupsHeldForSalePropertyPlantEquipment
core:TurnoverRevenue
core:UsefulLifeIntangibleAssetsYears